# Use an official Node.js runtime as a parent image
FROM node:16

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files to the container
COPY . .

# Expose the port the React app will run on
EXPOSE 3000

# Enable hot reload in Docker
ENV CHOKIDAR_USEPOLLING=true

# Start the React app in development mode
CMD ["npm", "start"]
